# Generated by Django 4.1.2 on 2022-11-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_skills_personal_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre completo'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='job',
            field=models.CharField(choices=[('0', 'Structural Engineer'), ('1', 'Associate Professor'), ('2', 'Financial Analyst'), ('3', 'Marketing Manager'), ('4', 'Help Desk Operator'), ('5', 'Account Coordinator'), ('6', 'Web Designer III'), ('7', 'Registered Nurse'), ('8', 'Librarian'), ('9', 'Junior Executive')], max_length=2),
        ),
    ]
