# Generated by Django 4.1.2 on 2022-11-30 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_personal_full_name_alter_personal_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='empleado'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='job',
            field=models.CharField(choices=[('0', 'Structural Engineer'), ('1', 'Associate Professor'), ('2', 'Financial Analyst'), ('3', 'Marketing Manager'), ('4', 'Help Desk Operator'), ('5', 'Account Coordinator'), ('6', 'Web Designer III'), ('7', 'Registered Nurse'), ('8', 'Librarian'), ('9', 'Junior Executive')], max_length=2, verbose_name='Trabajo'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
    ]
